# Generated by Django 3.1 on 2020-08-28 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_subcategoryparts'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategoryparts',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='list.categoryparts'),
        ),
    ]
